// Renders a board plan into an executable Figma Plugin API script for the
// `use_figma` MCP tool.
//
// The generated script obeys the rules from the figma-use-figjam skill that are
// easy to get wrong and expensive to debug:
//   - async IIFE wrapper, figma.closePlugin() on every path
//   - hex/255 color notation, or FigJam treats the color as "custom"
//   - appendChild BEFORE positioning, because x/y become section-local
//   - sections are participatory zones: sized to expected activity, never hugged
//     to seeded content, but grown if content would overflow
//   - a new connector's text.fontName is invalid, so it is set explicitly
//   - prompts and headers are TEXT nodes; stickies are reserved for participants
//   - figma.createPage() is unavailable in FigJam
//   - console.log is not returned to the caller, so IDs come back via `return`

import { LAYOUT } from './figjam-plan.mjs';

const j = (v) => JSON.stringify(v);
const hex = ([r, g, b]) => `h(0x${r.toString(16).padStart(2, '0')}, 0x${g.toString(16).padStart(2, '0')}, 0x${b.toString(16).padStart(2, '0')})`;

export function renderPluginScript(plan) {
  const sections = plan.sections.map((s) => ({
    key: s.key,
    name: s.name,
    header: s.header,
    body: s.body,
    x: s.x,
    y: s.y,
    width: s.width,
    height: s.height,
    tint: hex(s.tint.hex),
  }));

  return `(async () => {
  // Generated by pm-skills utility-figjam-board from ${plan.sourceFile}
  // Board: ${plan.title}
  const h = (r, g, b) => ({ r: r / 255, g: g / 255, b: b / 255 });
  const PAD = ${LAYOUT.padding};
  const HEADER_SIZE = ${LAYOUT.headerSize};
  const BODY_SIZE = ${LAYOUT.bodySize};
  const BLOCK_GAP = ${LAYOUT.blockGap};
  const CHARCOAL = h(0x1e, 0x1e, 0x1e);
  const FONT = { family: 'Inter', style: 'Medium' };

  // One font load up front. Every text node and connector label uses it, so
  // awaiting per-node would be a round trip per node for no benefit.
  await figma.loadFontAsync(FONT);

  const SECTIONS = ${j(sections.map(({ tint, ...rest }) => rest))};
  const TINTS = [${sections.map((s) => s.tint).join(', ')}];

  const made = {};
  const created = [];

  for (let i = 0; i < SECTIONS.length; i++) {
    const spec = SECTIONS[i];

    const section = figma.createSection();
    // Short navigational name; the visible header is a separate text node.
    section.name = spec.name;
    section.resize(spec.width, spec.height);
    section.x = spec.x;
    section.y = spec.y;
    section.fills = [{ type: 'SOLID', color: TINTS[i] }];

    const maxWidth = spec.width - PAD * 2;
    let cursorY = PAD;

    const header = figma.createText();
    header.fontName = FONT;
    header.characters = spec.header;
    header.fontSize = HEADER_SIZE;
    header.fills = [{ type: 'SOLID', color: CHARCOAL }];
    header.textAutoResize = 'HEIGHT';
    // appendChild first: x/y become section-local after reparenting.
    section.appendChild(header);
    header.resize(maxWidth, header.height);
    header.x = PAD;
    header.y = cursorY;
    cursorY += header.height + BLOCK_GAP;

    for (const line of spec.body) {
      const t = figma.createText();
      t.fontName = FONT;
      t.characters = line;
      t.fontSize = BODY_SIZE;
      t.fills = [{ type: 'SOLID', color: CHARCOAL }];
      t.textAutoResize = 'HEIGHT';
      section.appendChild(t);
      t.resize(maxWidth, t.height);
      t.x = PAD;
      t.y = cursorY;
      cursorY += t.height + BLOCK_GAP / 2;
    }

    // Participatory zone: keep the authored height so there is room to work,
    // and grow only if the seeded prompts would otherwise overflow.
    const needed = cursorY + PAD;
    if (needed > section.height) section.resize(spec.width, needed);

    made[spec.key] = section.id;
    created.push({ key: spec.key, id: section.id, name: section.name });
  }

  const CONNECTORS = ${j(plan.connectors)};
  for (const c of CONNECTORS) {
    const startId = made[c.from];
    const endId = made[c.to];
    if (!startId || !endId) continue;
    const conn = figma.createConnector();
    conn.connectorStart = { endpointNodeId: startId, magnet: 'AUTO' };
    conn.connectorEnd = { endpointNodeId: endId, magnet: 'AUTO' };
    conn.connectorStartStrokeCap = 'NONE';
    conn.connectorEndStrokeCap = 'ARROW_LINES';
    conn.strokes = [{ type: 'SOLID', color: h(0x75, 0x75, 0x75) }];
    if (c.label) {
      // A new connector's text.fontName is invalid until set explicitly.
      conn.text.fontName = FONT;
      conn.text.characters = c.label;
    }
  }

  // Legend, placed below the row. Every board gets one; a board without a
  // legend is a board only its author can read.
  const legend = figma.createSection();
  legend.name = 'Legend';
  legend.resize(${LAYOUT.sectionWidth}, 360);
  legend.x = 0;
  legend.y = ${LAYOUT.sectionHeight} + 200;
  legend.fills = [{ type: 'SOLID', color: h(0xf9, 0xf9, 0xf9) }];

  const legendLines = [
    'Text like this is a prompt placed when the board was built.',
    'Sticky notes are participant contributions. Add yours anywhere inside a section.',
    'Arrows run in workflow order and are labeled with the handoff between steps.',
    'Built from ${plan.sourceFile} by pm-skills utility-figjam-board.',
  ];
  let ly = PAD;
  const lTitle = figma.createText();
  lTitle.fontName = FONT;
  lTitle.characters = 'Legend';
  lTitle.fontSize = HEADER_SIZE;
  lTitle.fills = [{ type: 'SOLID', color: CHARCOAL }];
  lTitle.textAutoResize = 'HEIGHT';
  legend.appendChild(lTitle);
  lTitle.resize(${LAYOUT.sectionWidth} - PAD * 2, lTitle.height);
  lTitle.x = PAD;
  lTitle.y = ly;
  ly += lTitle.height + BLOCK_GAP;

  for (const line of legendLines) {
    const t = figma.createText();
    t.fontName = FONT;
    t.characters = line;
    t.fontSize = BODY_SIZE;
    t.fills = [{ type: 'SOLID', color: CHARCOAL }];
    t.textAutoResize = 'HEIGHT';
    legend.appendChild(t);
    t.resize(${LAYOUT.sectionWidth} - PAD * 2, t.height);
    t.x = PAD;
    t.y = ly;
    ly += t.height + BLOCK_GAP / 2;
  }
  if (ly + PAD > legend.height) legend.resize(${LAYOUT.sectionWidth}, ly + PAD);
  created.push({ key: 'legend', id: legend.id, name: legend.name });

  figma.closePlugin();
  // console.log is not returned to the caller; IDs come back through return.
  return { board: ${j(plan.title)}, sections: created };
})();
`;
}
